import type { AnalysisResult, ModelScoreComparisonEntry } from "../../lib/types";
import { TrustBadge } from "./TrustBadge";
import { ClaimCard } from "./ClaimCard";
import { ToneAlerts } from "./ToneAlerts";

interface Props {
  result: AnalysisResult;
  modelUsedLabel?: string;
  modelComparisons?: (ModelScoreComparisonEntry & { modelLabel?: string })[];
}

export function NutritionLabel({
  result,
  modelUsedLabel,
  modelComparisons = [],
}: Props) {
  const disputed = result.claims.filter(
    (c) => c.status === "disputed" || c.status === "misleading",
  ).length;
  const verified = result.claims.filter(
    (c) => c.status === "verified",
  ).length;
  const showComparison = modelComparisons.length > 1;
  const priorLimitAttempts =
    result.diagnostics?.attempts?.filter((attempt) => attempt.outcome === "limit") || [];

  return (
    <div className="bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden">
      {/* Header — score area, styled like a nutrition facts label */}
      <div className="p-4 border-b-[3px] border-zinc-700">
        <p className="text-[9px] uppercase tracking-[0.15em] text-zinc-500 font-bold mb-2">
          Credibility Report
        </p>
        <div className="flex items-start justify-between gap-3">
          <h2 className="text-[13px] font-semibold leading-snug text-zinc-200 flex-1">
            {result.title}
          </h2>
          <TrustBadge score={result.trustScore} grade={result.grade} />
        </div>
      </div>

      {/* Quick stats bar */}
      <div className="flex items-center gap-4 px-4 py-2 bg-zinc-800/40 border-b border-zinc-800 text-[11px]">
        <span className="text-zinc-400">
          <b className="text-emerald-400 font-semibold">{verified}</b>{" "}
          verified
        </span>
        <span className="text-zinc-400">
          <b className="text-red-400 font-semibold">{disputed}</b>{" "}
          flagged
        </span>
        <span className="text-zinc-400">
          <b className="text-zinc-300 font-semibold">
            {result.claims.length}
          </b>{" "}
          total
        </span>
        {result.toneAlerts.length > 0 && (
          <span className="text-amber-400 ml-auto font-medium">
            {result.toneAlerts.length} alert
            {result.toneAlerts.length !== 1 ? "s" : ""}
          </span>
        )}
      </div>

      {modelUsedLabel && (
        <div className="px-4 py-2 border-b border-zinc-800/60 bg-zinc-900/50">
          <p className="text-[11px] text-zinc-500">
            Score generated by{" "}
            <span className="text-zinc-300 font-medium">{modelUsedLabel}</span>
          </p>
        </div>
      )}

      {/* Summary */}
      <div className="px-4 py-3 border-b border-zinc-800/60">
        <p className="text-[12px] text-zinc-400 leading-relaxed">
          {result.summary}
        </p>
      </div>

      {priorLimitAttempts.length > 0 && (
        <div className="px-4 py-3 border-b border-zinc-800/60 bg-zinc-950/30">
          <p className="text-[9px] uppercase tracking-[0.15em] text-zinc-500 font-bold mb-1.5">
            Fallback Notes
          </p>
          <p className="text-[11px] text-zinc-400 leading-relaxed">
            A previous model attempt was limited before this result completed:
          </p>
          <div className="mt-2 space-y-1.5">
            {priorLimitAttempts.map((attempt) => (
              <p
                key={`${attempt.modelId}-${attempt.attemptedAt}`}
                className="text-[11px] text-zinc-500 leading-relaxed"
              >
                {attempt.modelId}: {attempt.message}
              </p>
            ))}
          </div>
        </div>
      )}

      {result.analysisScope && (
        <div className="px-4 py-3 border-b border-zinc-800/60 bg-zinc-950/20">
          <p className="text-[9px] uppercase tracking-[0.15em] text-zinc-500 font-bold mb-1.5">
            Analysis Scope
          </p>
          <p className="text-[11px] text-zinc-400 leading-relaxed">
            {result.analysisScope.note}
          </p>
        </div>
      )}

      {showComparison && (
        <div className="px-4 py-3 border-b border-zinc-800/60">
          <p className="text-[9px] uppercase tracking-[0.15em] text-zinc-500 font-bold mb-2">
            Model Score Comparison
          </p>
          <div className="space-y-1.5">
            {modelComparisons.map((entry) => (
              <div
                key={`${entry.modelId}-${entry.analyzedAt}`}
                className="flex items-center justify-between gap-3 text-[11px]"
              >
                <span className="text-zinc-400 truncate">
                  {entry.modelLabel || entry.analysisModel || entry.modelId}
                </span>
                <span className="font-semibold text-zinc-200 tabular-nums">
                  {entry.trustScore} ({entry.grade})
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Claims breakdown */}
      <div className="border-b border-zinc-800/60">
        <div className="px-4 py-2 bg-zinc-800/30">
          <p className="text-[9px] uppercase tracking-[0.15em] text-zinc-500 font-bold">
            Claims Breakdown
          </p>
        </div>
        <div className="divide-y divide-zinc-800/40">
          {result.claims.map((claim) => (
            <ClaimCard key={claim.id} claim={claim} />
          ))}
        </div>
      </div>

      {/* Tone alerts */}
      {result.toneAlerts.length > 0 && (
        <ToneAlerts alerts={result.toneAlerts} />
      )}

      {/* Footer */}
      <div className="px-4 py-2 bg-zinc-800/20">
        <p className="text-[10px] text-zinc-600 text-center">
          Analyzed {new Date(result.analyzedAt).toLocaleString()}
        </p>
      </div>
    </div>
  );
}
